---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        testnet: {{ .Values.deployment.testnet }}
        role: {{ default "undefined" .Values.node.role }}
        class: {{ default "undefined" .Values.node.class }}
        version: {{ trunc 8 (split ":" .Values.deployment.image)._1 | trimSuffix "-" }}
        syncStatus: INIT
      {{- if .Values.node.metrics.enabled }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.node.metrics.port | quote }}
        prometheus.io/path: '/metrics'
      {{- end }}
    spec:
      initContainers:
        {{ if .Values.node.libp2pKeys.enabled -}}
        - name: fix-libp2p-perms
          image: busybox:latest
          command:
            - sh
            - -c
            - cp /libp2p-keys/* /root/libp2p-keys && chmod -R 0700 /root/libp2p-keys/
          volumeMounts:
            - name: {{ .Release.Name }}-mounted-libp2p-keys
              mountPath: /libp2p-keys
            - name: {{ .Release.Name }}-fixed-libp2p-keys
              mountPath: /root/libp2p-keys
        {{- end }}
        {{ if .Values.node.walletKeys.enabled -}}
        - name: fix-mina-perms
          image: busybox:latest
          command:
            - sh
            - -c
            - cp /mina-keys/* /root/mina-keys/ && chmod -R 0700 /root/mina-keys/
          volumeMounts:
            - name: {{ .Release.Name }}-mounted-mina-keys
              mountPath: /mina-keys
            - name: {{ .Release.Name }}-fixed-mina-keys
              mountPath: /root/mina-keys
        {{- end }}
      containers:
        - name: mina
          resources:
            limits:
            requests:
              memory: {{ .Values.requests.memory }}
              cpu: {{ .Values.requests.cpu }}
          image: {{ .Values.deployment.image }}
          {{ if .Values.deployment.customEntrypoint.enabled -}}
          command: [{{ .Values.deployment.customEntrypoint.entrypoint }}]
          {{- end }}
          args: [ "daemon",
            {{- if .Values.deployment.uptime.enabled }}
            "--uptime-url", {{ .Values.deployment.uptime.url | quote }},
            "--uptime-submitter-key", "/root/mina-keys/{{ .Values.node.name }}-key",
            {{- end }}
            {{- if .Values.node.statsUrl }}
            "--node-status-url", {{ .Values.node.statsUrl | quote }},
            {{- end }}
            {{- if .Values.node.errorsUrl }}
            "--node-error-url", {{ .Values.node.errorsUrl | quote }},
            {{- end }}
            {{- if .Values.node.fileLogLevel }}
            "--file-log-level", {{ .Values.node.fileLogLevel | quote }},
            {{- end -}}
            {{- if .Values.node.logLevel }}
            "--log-level", {{ .Values.node.logLevel | quote }},
            {{- end -}}
            "--client-port", "$(DAEMON_CLIENT_PORT)",
            "--rest-port", "$(MINA_GRAPHQL_PORT)",
            "--external-port", "$(DAEMON_EXTERNAL_PORT)",
            {{- if .Values.node.metrics.enabled }}
            "--metrics-port", "$(DAEMON_METRICS_PORT)",
            {{- end -}}
            {{- if .Values.node.exposeGraphql }}
            "--insecure-rest-server",
            {{- end -}}
            {{- if .Values.node.maxConnections }}
            "--max-connections", {{ .Values.node.maxConnections | quote }},
            {{- end -}}
            {{- if .Values.deployment.peerListURL }}
            "--peer-list-url", {{ .Values.deployment.peerListURL | quote }},
            {{- end -}}
            {{- if .Values.deployment.runtimeConfig }}
            "--config-file", "/config/daemon.json",
            {{- end }}
            {{- if .Values.node.libp2pKeys.enabled }}
            {{ (eq .Values.deployment.testnet "berkeley") |ternary "--libp2p-keypair" "--discovery-keypair" |quote }}, "/root/libp2p-keys/{{ .Values.node.name }}-libp2p",
            {{- end -}}
            {{- with .Values.node }}
            {{- if and .walletKeys.enabled .daemonMode.blockProducer }}
            "--block-producer-key", "/root/mina-keys/{{ $.Values.node.name }}-key",
            {{- end }}
            {{- if and .walletKeys.enabled .daemonMode.snarkWorker }}
            "--run-snark-worker", "/root/mina-keys/{{ $.Values.node.name }}-key",
            {{- end }}
            {{- end }}
            {{- if .Values.node.daemonMode.seed }}
            "--seed",
            {{- end }}
            {{- range .Values.deployment.seedPeers }}
            "--peer", {{ . | quote }},
            {{- end }}
            {{- if .Values.deployment.uploadBlocksToGCloud }}
            "--upload-blocks-to-gcloud", "true",
            {{- end }}
            {{- if .Values.node.archive.enabled }}
            "--archive-address", {{ .Values.node.archive.address }},
            {{- end }}
            {{- if .Values.node.seedFlags }}
            "--enable-peer-exchange", "true", "-seed",
            {{- end}}
            "--log-json"
          ]
          env:
            - name: MINA_NETWORK
              value: {{ .Values.deployment.testnet }}
            - name: MINA_GRAPHQL_PORT
              value: {{ .Values.node.ports.graphql | quote }}
            - name: DAEMON_CLIENT_PORT
              value: {{ .Values.node.ports.client | quote }}
            {{- if .Values.node.metrics.enabled }}
            - name: DAEMON_METRICS_PORT
              value: {{ .Values.node.metrics.port | quote }}
            {{- end }}
            - name: MINA_CLIENT_TRUSTLIST
              value: "10.0.0.0/8"
            {{- if .Values.deployment.uploadBlocksToGCloud }}
            - name: GCLOUD_KEYFILE
              value: "/gcloud/keyfile.json"
            - name: GCLOUD_BLOCK_UPLOAD_BUCKET
              value: "mina_network_block_data"
            {{- end }}
            - name: DAEMON_EXTERNAL_PORT
              value: {{ .Values.node.ports.p2p | quote }}
            {{- if .Values.node.libp2pKeys.enabled }}
            - name: MINA_LIBP2P_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: "libp2p-password"
            {{- end }}
            {{- if .Values.node.walletKeys.enabled }}
            - name: MINA_PRIVKEY_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: "wallet-password"
            {{- end }}
            {{- if .Values.deployment.uptime.enabled }}
            - name: UPTIME_PRIVKEY_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: "wallet-password"
            {{- end }}
          ports:
            - name: client-port
              protocol: TCP
              containerPort: {{ .Values.node.ports.client }}
            - name: graphql-port
              protocol: TCP
              containerPort: {{ .Values.node.ports.graphql }}
            {{- if .Values.node.metrics.enabled }}
            - name: metrics-port
              protocol: TCP
              containerPort: {{ .Values.node.metrics.port }}
            {{- end }}
            - name: external-port
              protocol: TCP
              containerPort: {{ .Values.node.ports.p2p }}
{{- $data := dict "name" .Values.node.name "healthcheck" .Values.healthcheck }}
{{- include "healthcheck.node.allChecks" $data | indent 10 }}
          imagePullPolicy: Always
          volumeMounts:
            {{- if .Values.node.libp2pKeys.enabled }}
            - name: {{ .Release.Name }}-fixed-libp2p-keys
              mountPath: /root/libp2p-keys
            {{- end }}
            {{- if .Values.node.walletKeys.enabled }}
            - name: {{ .Release.Name }}-fixed-mina-keys
              mountPath: /root/mina-keys
            {{- end }}
            {{- if .Values.deployment.uploadBlocksToGCloud }}
            - name: {{ .Release.Name }}-gcloud-keyfile
              mountPath: "/gcloud/"
            {{- end }}
            {{- if .Values.deployment.runtimeConfig }}
            - name: {{ .Release.Name }}-runtime-config
              mountPath: "/config/"
            {{- end }}
      volumes:
        {{- if .Values.deployment.runtimeConfig }}
        - name: {{ .Release.Name }}-runtime-config
          configMap:
            name: {{ .Release.Name }}-runtime-config
        {{- end }}
        {{- if .Values.node.walletKeys.enabled }}
        - name: {{ .Release.Name }}-mounted-mina-keys
          secret:
            secretName: {{ .Release.Name }}
            defaultMode: 0600
            items:
              - key: {{ .Values.node.name }}-key
                path: {{ .Values.node.name }}-key
              - key: {{ .Values.node.name }}-key.pub
                path: {{ .Values.node.name }}-key.pub
        - name: {{ .Release.Name }}-fixed-mina-keys
          emptyDir: {}
        {{- end }}
        {{- if .Values.node.libp2pKeys.enabled }}
        - name: {{ .Release.Name }}-mounted-libp2p-keys
          secret:
            secretName: {{ .Release.Name }}
            defaultMode: 0600
            items:
              - key: {{ .Values.node.name }}-libp2p
                path: {{ .Values.node.name }}-libp2p
              - key: {{ .Values.node.name }}-libp2p.peerid
                path: {{ .Values.node.name }}-libp2p.peerid
        - name: {{ .Release.Name }}-fixed-libp2p-keys
          emptyDir: {}
        {{- end }}
        {{- if .Values.node.uploadBlocksToGCloud }}
        - name: gcloud-keyfile
          secret:
            secretName: gcloud-keyfile
            defaultMode: 0400
            items:
              - key: keyfile
                path: keyfile.json
        {{- end }}
