---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.node.name }}
data:
  key-password: {{ .Values.node.secrets.keyPassword }}
  libp2p-password: {{ .Values.node.secrets.libp2pPassword }}
  {{ .Values.node.name }}-key: {{ .Values.node.secrets.nodeKey }}
  {{ .Values.node.name }}-key.pub: {{ .Values.node.secrets.nodeKeyPub }}
  {{ .Values.node.name }}-libp2p: {{ .Values.node.secrets.nodeLibp2p }}
  {{ .Values.node.name }}-libp2p.peerid: {{ .Values.node.secrets.nodeLibp2pPeerid }}
---
