---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  key-password: {{ .Values.node.secrets.keyPassword | b64enc }}
  libp2p-password: {{ .Values.node.secrets.libp2pPassword | b64enc }}
  {{ .Values.node.name }}-key: {{ .Values.node.secrets.produceBlocksKey | b64enc }}
  {{ .Values.node.name }}-key.pub: {{ .Values.node.secrets.produceBlocksKeyPub | b64enc }}
  {{ .Values.node.name }}-libp2p: {{ .Values.node.secrets.discoveryLibp2p | b64enc }}
  {{ .Values.node.name }}-libp2p.peerid: {{ .Values.node.secrets.discoveryLibp2pPeerid | b64enc }}
