---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  wallet-password: {{ .Values.node.secrets.walletPassword | b64enc }}
  libp2p-password: {{ .Values.node.secrets.libp2pPassword | b64enc }}
  {{ .Values.node.name }}-key: {{ .Values.node.secrets.walletKey | b64enc }}
  {{ .Values.node.name }}-key.pub: {{ .Values.node.secrets.walletPub | b64enc }}
  {{ .Values.node.name }}-libp2p: {{ .Values.node.secrets.discoveryLibp2p | b64enc }}
  {{ .Values.node.name }}-libp2p.peerid: {{ .Values.node.secrets.discoveryLibp2pPeerid | b64enc }}
  {{- if or .Values.deployment.storeBlocks.gcp.enabled .Values.deployment.storeBlocks.aws.enabled }}
  gcloud-keyfile: {{ .Values.deployment.storeBlocks.gcp.keyfile | b64enc }}
  {{- end }}
