---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.daemon.name }}
data:
  key-password: {{ .Values.daemon.secrets.keyPassword }}
  libp2p-password: {{ .Values.daemon.secrets.libp2pPassword }}
  {{ .Values.daemon.name }}-key: {{ .Values.daemon.secrets.nodeKey }}
  {{ .Values.daemon.name }}-key.pub: {{ .Values.daemon.secrets.nodeKeyPub }}
  {{ .Values.daemon.name }}-libp2p: {{ .Values.daemon.secrets.nodeLibp2p }}
  {{ .Values.daemon.name }}-libp2p.peerid: {{ .Values.daemon.secrets.nodeLibp2pPeerid }}
