{{- if .Values.node.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  endpoints:
    - interval: 30s
      port: metrics-port
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Values.deployment.testnet }}
  targetLabels:
  - testnet
  - role
{{- end }}
