{{- if .Values.node.exposeGraphql }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http-graphql
    protocol: TCP
    port: 80
    targetPort: {{ .Values.node.ports.graphql }}
{{- end }}
