apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmina-node.fullname" . }}
data:
  wallet-key: {{ .Values.node.wallet.privateKey | b64enc }}
  wallet-key.pub: {{ .Values.node.wallet.publicKey | b64enc }}
  libp2p-key: {{ .Values.node.libp2p.privateKey | b64enc }}
  libp2p-key.pub: {{ .Values.node.libp2p.publicKey | b64enc }}
