---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{- with .Values.deployment.configMap }}
              - name: {{ .volumeName }} 
                mountPath: {{ .mountPath | quote }}
                subPath: {{ .subPath | quote }}
            {{- end }}
      volumes:
        {{- with .Values.deployment.configMap }}
          - name: {{ .volumeName }}
            configMap:
              name: {{ .name }}
        {{- end }}
