{{- if .Values.archive.runtimeConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "archive.fullname" . }}-runtime-config
  labels:
    app: {{ template "archive.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ .Values.archive.runtimeConfig | quote }}
{{- end }}
