apiVersion: v1
kind: Service
metadata:
  name: {{ include "staking-ledgers-fetcher.fullname" . }}
  labels:
    {{- include "staking-ledgers-fetcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "staking-ledgers-fetcher.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
