{{- if .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  {{- range .items }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
{{- end }}
{{- end }}
