apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  {{- if and (eq .Values.type "statefulset") (or (not (hasKey .Values.service "clusterIP")) (eq .Values.service.clusterIP "None")) }}
  clusterIP: None
  {{- else if and (hasKey .Values.service "clusterIP") (ne .Values.service.clusterIP "") (ne .Values.service.clusterIP "None") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity.enabled }}
  sessionAffinity: {{ .Values.service.sessionAffinity.type }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeoutSeconds }}
  {{- end }}
