apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mina-payout-reports.fullname" . }}
data:
  entrypoint-initdb.sh: |-
{{ .Files.Get "files/entrypoint_initdb.sh" | indent 4 }}
  mina-report-cron.sh: |-
{{ .Files.Get "files/mina_report_cron.sh" | indent 4 }}
