apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mina-payout-reports.fullname" . }}-web
  labels:
    {{- include "mina-payout-reports.labels" . | nindent 4 }}
    {{- include "mina-payout-reports.selectorLabelsWeb" . | nindent 4 }}
spec:
  {{- with .Values.payoutReportsWeb }}
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "mina-payout-reports.selectorLabelsWeb" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mina-payout-reports.selectorLabelsWeb" $ | nindent 8 }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mina-payout-reports.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: payout-reports-web
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: REACT_APP_API_URL
              value: {{ .backendPublicUrl | quote }}

            {{- if .extraEnvVars }}
            {{- toYaml .extraEnvVars | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 120
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
