apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mina-payout-reports.fullname" . }}
  labels:
    {{- include "mina-payout-reports.labels" . | nindent 4 }}
    {{- include "mina-payout-reports.selectorLabelsApi" . | nindent 4 }}
data:
  gcp-sa-json: {{ .Values.payoutReportsApi.gcpServiceAccount | toString | b64enc }}
