apiVersion: v1
kind: Service
metadata:
  name: {{ include "mina-payout-reports.fullname" . }}-api
  labels:
    {{- include "mina-payout-reports.labels" . | nindent 4 }}
    {{- include "mina-payout-reports.selectorLabelsApi" . | nindent 4 }}
spec:
  type: {{ .Values.leaderboardApi.service.type }}
  ports:
    - port: {{ .Values.leaderboardApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mina-payout-reports.selectorLabelsApi" . | nindent 4 }}
