apiVersion: v1
kind: Service
metadata:
  name: {{ include "mina-payout-reports.fullname" . }}-web
  labels:
    {{- include "mina-payout-reports.labels" . | nindent 4 }}
    {{- include "mina-payout-reports.selectorLabelsWeb" . | nindent 4 }}
spec:
  type: {{ .Values.leaderboardWeb.service.type }}
  ports:
    - port: {{ .Values.leaderboardWeb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mina-payout-reports.selectorLabelsWeb" . | nindent 4 }}
