---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kyc-management-app.fullname" . }}
  labels:
    {{- include "kyc-management-app.labels" . | nindent 4 }}
data:
  gcp-sa-json: {{ .Values.gcpServiceAccount | toString | b64enc }}

