apiVersion: v1
kind: Service
metadata:
  name: {{ include "kyc-management-app.fullname" . }}-hook
  labels:
    {{- include "kyc-management-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: hook
    {{- include "kyc-management-app.selectorLabels" . | nindent 4 }}
