apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmina-p2p-replayer.fullname" . }}
  labels:
    {{- include "openmina-p2p-replayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: external-port
      protocol: TCP
      name: tcp-p2p
  selector:
    {{- include "openmina-p2p-replayer.selectorLabels" . | nindent 4 }}
