apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redisinsight.fullname" . }}-headless
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "redisinsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redisinsight.selectorLabels" . | nindent 8 }}
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redisinsight.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: redisinsight-volume
          persistentVolumeClaim:
            claimName: {{ include "redisinsight.fullname" . }}
      {{- end }}
      containers:
        - name: redisinsight
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-ui
              containerPort: 5540
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: "/data"
              name: redisinsight-volume
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.server.extraEnvVars }}
            {{- toYaml .Values.server.extraEnvVars | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
