deployment:
  image:
    repository: 673156464838.dkr.ecr.us-west-2.amazonaws.com/block-producers-uptime
    pullPolicy: IfNotPresent
    tag: "1.2.0-test-1"
  replicaCount: 1
  secrets:
    credentialFileName: "block-producers-uptime-gcp-sa-credential"
    credentialFilePath: "test"
    credentialFileContent: "test"

service:
  type: LoadBalancer
  port: 8080
  externalTrafficPolicy: Local

ingress:
  class: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/preserve-client-ip: "true"
  rules:
    paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 8080
