---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  {{ .Values.deployment.secrets.credentialFileName }}: {{ .Values.deployment.secrets.credentialFileContent | toString | b64enc }}
