---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  {{ .Values.deployment.secrets.credentialFile.name }}: {{ .Values.deployment.secrets.credentialFile.content | toString | b64enc }}