apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpt-survey-summarizer.fullname" . }}-api
  labels:
    {{- include "gpt-survey-summarizer.labels" . | nindent 4 }}-api
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpt-survey-summarizer.selectorLabels" . | nindent 6 }}-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpt-survey-summarizer.selectorLabels" . | nindent 8 }}-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpt-survey-summarizer.serviceAccountName" . }}-api
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            {{- toYaml .Values.api.args | nindent 12 }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: openAiApiKey
            - name: REDIS_HOST
              value: {{ include "gpt-survey-summarizer.fullname" . }}-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpt-survey-summarizer.fullname" . }}
                  key: redisPassword
            - name: REDIS_PORT
              value: {{ .Values.redis.master.service.ports.redis | quote }}
            - name: GSS_LOG_LEVEL
              value: {{ .Values.config.gssLogLevel | quote }}
          {{- if .Values.api.extraEnvVars }}
            {{- toYaml .Values.api.extraEnvVars | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
