{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "decentralized-treasury.databaseSecretName" . }}
  labels:
    {{- include "decentralized-treasury.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretUrlKey }}: {{ include "decentralized-treasury.databaseUrl" . | quote }}
{{- end }}
